### ISSUE TITLE
Requisitos

### ISSUE THREAD

**Issue by brenoalvs** [wp-rio/wp-rio#1]
Vamos levantar os requisitos antes de começar a desenvolver, certo?

**Comment by theandersonn** [comment]
Sim, vamos!
O start tem ser pela arquitetura de informações que montamos.

**Comment by marioernestoms** [comment]
Essa é a ideia

**Comment by brenoalvs** [comment]
Estava dando uma lida no doc do site, acho que pelo que está lá não vamos precisar de nenhum CPT por enquanto.

Talvez no máximo um de meetups, pra postar coisas relacionadas à edição.
Mas isso poderia ser feito, com posts no blog.

Então se for só o caso de "encapar" o site atual, transformamos isso aqui num child theme e depois fazemos um tema e plugin para o site.

**Comment by marioernestoms** [comment]
É uma idéia vamos analisar isso, e se for isso mesmo envelopamos o site,
depois que o Burity terminar a logo.

Em quarta-feira, 13 de maio de 2015, Breno Alves notifications@github.com
escreveu:

> Estava dando uma lida no doc do site, acho que pelo que está lá não vamos
> precisar de nenhum CPT por enquanto.
> 
> Talvez no máximo um de meetups, pra postar coisas relacionadas à edição.
> Mas isso poderia ser feito, com posts no blog.
> 
> Então se for só o caso de "encapar" o site atual, transformamos isso aqui
> num child theme e depois fazemos um tema e plugin para o site.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wp-rio/wp-rio/issues/1#issuecomment-101803105.

## 

Att
Mario Ernesto
Tel: +55 (21) 99516-1458

**Comment by brenoalvs** [comment]
Já definimos tudo, vamos pegar o que definimos durante as reuniões e organizar nas issues!
