### ISSUE TITLE
WordCamp/Single: Ajustar diagramação das thumbs

### ISSUE THREAD

**Issue by theandersonn** [wp-rio/wp-rio#100]
A diagramação das thumbs estão quebrando, precisamos ajustar.

![wordcamp-single](https://cloud.githubusercontent.com/assets/5203138/17192631/b993a308-5425-11e6-9d76-642f858a06e5.png)

**Comment by rodrigocka** [comment]
Primeiramente, precisamos definir quantos itens devem aparecer para cada tamanho de tela. Nesse caso, acho que devemos colocar 3 para >992px, 2 para >768 e 1 para <768.
Além dos slides dos WordCamps (single-wordcamps.php), temos o mesmo erro nos Meetups (archive-meetups.php) se um dos títulos passar para 2 linhas.

<img width="693" src="https://cloud.githubusercontent.com/assets/14809680/17200371/e5709dd4-545a-11e6-8307-8112096b9623.PNG">
Se ninguém estiver trabalhando na issue, pode me passar.

**Comment by theandersonn** [comment]
@rodrigocka tá de boa pode pegar essa issue! Assine pra demarcar que você está trabalhando nela.

Nos meetups até 768 exibe duas thumbs e a partir deste breakpoint exibe três.

E nos meetups eles segue um título padrão, acho que não atingirão duas linhas, mas se desejar prevenir, pode mandar ajuste tb para os meetups.
