### ISSUE TITLE
[page: comunidade-wp-rio] Diminuir espaçamento entre foto e descrição

### ISSUE THREAD

**Issue by theandersonn** [wp-rio/wp-rio#103]
Na página '[comunidade-wp-rio](http://wprio.org/comunidade-wp-rio)' precisamos diminuir o espaçamento entre a foto e a respectiva descrição.

![wp-rio-espacamento](https://cloud.githubusercontent.com/assets/5203138/17672428/adc5d9a2-62f2-11e6-938f-837f80cfbc18.jpg)

**Comment by rodrigocka** [comment]
Posso fazer e aproveito para melhorar na exibição em smartphones.

![snap 2016-08-15 at 15 45 03](https://cloud.githubusercontent.com/assets/14809680/17675405/09fc016c-6300-11e6-8fe1-fc3fff111024.png)

**Comment by theandersonn** [comment]
Tá falado @rodrigocka! :metal:
Add você na assinatura pra identificar que você está trabalhando nesta issue.

**Comment by theandersonn** [comment]
Resolvido https://github.com/wprio/wprio/pull/110
