### ISSUE TITLE
[Google] Mensagem - Esse site pode ter sido invadido

### ISSUE THREAD

**Issue by theandersonn** [wp-rio/wp-rio#133]
Estamos com problemas no Google, está exibindo a mensagem "Esse site pode ter sido invadido".

![print-wprio-google](https://cloud.githubusercontent.com/assets/5203138/19778240/9d3d2058-9c5a-11e6-9617-53929cd5d8a6.png)

**Comment by theandersonn** [comment]
@gugaalves e @felipepavao  Tem como dar uma olhada por favor?

**Comment by felipepavao** [comment]
O site foi invadido. Exploraram uma falha no arquivo single-meetup.php
