### ISSUE TITLE
Repositório para organização e documentação dos Meetups

### ISSUE THREAD

**Issue by theandersonn** [wp-rio/wp-rio#2]
Sugestão de criação de um repositório para organização e documentação dos Meetups.

**Estrutura**

Meetups
- 1-meetup-wp-rj
  _Serviço e Slides. (sugestão de conteúdo de cada repositório)_
- 2-meetup-wp-rj
- 3-meetup-wp-rj
- 4-meetup-wp-rj
- 5-meetup-wp-rj
- 6-meetup-wp-rj
- 7-meetup-wp-rj
- 8-meetup-wp-rj
- 9-meetup-wp-rj

**Comment by gugaalves** [comment]
Não vejo porque colocar os slides aqui. Usaria o github apenas para guardar a parte técnica mesmo, como tema e plugins usados no site, PSD que foi usado pra fazer o site, etc.
Não temos que fazer quem não é dev vir no github pra pegar um slide de palestra né, bota no slideshare!

**Comment by theandersonn** [comment]
A ideia não é forçar quem não é dev ou não está ambientado com o Github vir aqui e sim servir melhor que curte a plataforma.

A nossa principal fonte de informações e referências será o site.

Os Slides ficarão no slideshare, as fotos ficarão numa galeria apropriada e etc... cada informação em sua respectiva origem. A sugestão é servir informação pra quem curte e busca essa informação aqui.

Exemplo:

9 Meetup WordPress RJ

Realizado dia  23 de junho de 2015
Local: ESPM RJ

Palestras:

Palestra 1 (link da apresentação no slideshare)
Palestra 2 (link da apresentação no slideshare)

Fotos: (link das fotos numa galeria)

Rewiews:

Link de artigos com rewiews das apresentações

**Comment by gugaalves** [comment]
Ah sim, ai sim! :D

**Comment by marioernestoms** [comment]
Acho válido usar esse repositório só pra servir códigos e psds usados em alguma palestra, fora isso não vale.

**Comment by theandersonn** [comment]
@marioernestoms Não acha de desta forma perdemos uma oportunidade de socializar o conteúdo dos meetups aqui?

No meu caso o GitHub é a minha rede social nº1, é a que passo mais tempo, e pesquiso por conteúdo, sinto falta dessas informações aqui, para o meu perfil não está sendo servido nenhum conteúdo.

**Comment by gugaalves** [comment]
É sua rede social número 1 pq vc é DEV Anderson, só é por isso. Nosso foco não é só a galera dev, dev é só uma parte do nosso público. Temos q ir pro melhor canal q atenda a todos.

**Comment by theandersonn** [comment]
@gugaalves Entendo, concordo e repito: nosso principal canal será o site onde as informações serão disponibilizadas mais amplamente e de fácil acesso.

Entendo que uma coisa não invalida outra ou por documentarmos aqui estaremos dando preferência aos devs, apenas estamos servindo conteúdo numa rede social.

Exemplo termos conta no Twitter, Facebook e G+

**Comment by marioernestoms** [comment]
O problema é ter que criar o hábito de postar aqui, postar no site, postar no facebook, como o @gugaalves disse e concordo plenamente é uma rede social para devs é a sua numero 1 mas até mesmo entre os devs não é. eu mesmo não uso quase. Então acho muito melhor centrar agora esse conteudo de slides e etc no meetup.com e futuramente no site.

**Comment by theandersonn** [comment]
Aqui no GitHub posso tocar de boa esse repositório.

**Comment by marioernestoms** [comment]
Eu não vejo um retorno maneiro em postar aqui, mas também não sou contra vc tocar o repositório.

**Comment by gugaalves** [comment]
Eu sou a favor de inicialmente se gastar tempo no que é principal, e só depois pensar no que é secundário.

**Comment by brenoalvs** [comment]
Entendo o ponto de socializarmos por aqui, mas também não acho uma boa um repositório só pra isso, podemos socializar por aqui de outras formas mais eficazes.

Como já disse, precisamos tentar tocar alguns projetos com desenvolvedores da comunidade. Não só fazer um meetup de temas e plugins, mas expor algum problema real e fazer a comunidade carioca se mexer para resolvê-lo.

Acredito que apenas dessa forma vamos conseguir ser vistos como uma comunidade forte de desenvolvimento.

**Comment by theandersonn** [comment]
Ok, entendi a opinião de vcs.

Quanto a questão de tempo, eu me coloco a disposição pra tocar, estruturar e manter organizado esse repositório.

Quando acharem conveniente e estiverem de acordo, iniciemos esse repositório.

E um detalhe é: Não utilizarmos essa conta apenas para essa finalidade, esse será um dos repositórios que criaremos. Temos esse público aqui e não estamos servimos esse conteúdo.

Fico preocupado em pensarmos em muitas coisas e não colocarmos em pratica.

@brenoalvs, sugestões? Que ótimo, podemos discuti-las em outra Issue.

Por mim, podemos fechar essa issue e re-abrir quando for conveniente. Qualquer coisa reabrimos  ;)
