### ISSUE TITLE
[Header] Menu mobile

### ISSUE THREAD

**Issue by brenoalvs** [wp-rio/wp-rio#25]
Finalizar menu mobile:
- Adicionar botão
- Reestilizar navegação.

**Comment by theandersonn** [comment]
@brenoalvs _Update em 15/06/16 para expandir a explicação da tarefa._

Reestruturar header.php com a implementação das respectivas classes do bootstrap para o funcionamento do menu hamburguer [navbar-collapse]

**Comment by brenoalvs** [comment]
Docs:
http://getbootstrap.com/components/#navbar

Exemplo:
https://getbootstrap.com/examples/navbar/

Atualmente está assim em resoluções menores:
![screen shot 2016-06-20 at 7 00 44 am](https://cloud.githubusercontent.com/assets/5307192/16190796/7df46c3c-36b7-11e6-8912-ce8155c9194e.png)

**Comment by lazaroalvarenga** [comment]
Essa issue ainda tá aberta, né?
Posso ajudar nela? =]

**Comment by brenoalvs** [comment]
@lazaroalvarenga deve! rs
@marioernestoms vou passar pra ele, sei que tu anda enrolado!

**Comment by marioernestoms** [comment]
@brenoalvs tranquilo passa sim, vc sabe como ta punk na empresa esse mes

**Comment by marioernestoms** [comment]
@lazaroalvarenga pode pegar cara, eu ando bem enrolado de trampo e nao vou conseguir ver isso. :)

**Comment by lazaroalvarenga** [comment]
Opa, oka @marioernestoms e @brenoalvs. Hoje eu pego nisso e mando o pr. ;)

**Comment by rodrigocka** [comment]
Fala pessoal.
Como não tinha mais nenhuma issue para trabalhar, tirei um tempo para ver essa com objetivo de aprender e já resolvi.
Se ainda não tiverem a correção, posso fazer o PR?

**Comment by brenoalvs** [comment]
@rodrigocka deve! Manda aí que dou uma revisada e faço o merge!

**Comment by rodrigocka** [comment]
@brenoalvs Feito.
Só lembrando que o foco foi apenas na correção do toggle, e que precisamos melhorar o visual e ordenação dos menus.

![selection_007](https://cloud.githubusercontent.com/assets/14809680/17870950/ea94de76-688f-11e6-9e24-2799e18778df.png)

![selection_008](https://cloud.githubusercontent.com/assets/14809680/17870954/f0f25604-688f-11e6-85ef-c138fb5d8ddd.png)

![selection_009](https://cloud.githubusercontent.com/assets/14809680/17870961/f4e8bb54-688f-11e6-949a-b376d0eeb801.png)

**Comment by theandersonn** [comment]
Resolvido PR #111
