### ISSUE TITLE
Organizaçao hierárquica de pastas

### ISSUE THREAD

**Issue by miguelsmuller** [wp-rio/wp-rio#27]
Sei que no momento o foco é o front mas deixo a isso aqui pra sugerir uma organização melhor das pastas para facilitar a colaboração de todos:

Fica a seguinte sugestão:

```
- wp-rio
|----public (entraria o wordpress em si)
|----sample (entraria um dump pra ficar + fácil contribuir)
|----design (entraria o psd, mesmo que poucos)
```

Aproveito para sugerir uma mudança mas forte também e por favor não me xinguem...
mudar o nome do reposório de `wp-rio` para `wprio` e a pasta do tema para `wprio-theme`

**Comment by brenoalvs** [comment]
Como já conversamos no Slack, o `wprio` a gente já usa em tudo, foi um mole mesmo.
O nome da pasta do tema já não sei se é bom mudar, talvez só deixar como `wprio` mesmo, pode ser que nem dê pra entrar no repositório, se tiver o `-theme`.

No mais, também concordo de darmos uma organizada melhor nas pastas pra quem for contribuir.
Mas isso é pra depois, temos que discutir como ficaria o auto-deploy do site.

**Comment by brenoalvs** [comment]
@felipepavao se mudarmos o nome do repositório, pode dar problema na hora do deploy automático, né?

**Comment by felipepavao** [comment]
@brenoalvs sem dúvida. Mas seria uma questão de refazer o esquema de deployment. 
Podemos falar sobre isso na semana...

**Comment by brenoalvs** [comment]
@miguelsmuller estou fechando isso aqui.
Estamos tomando outra estratégia para o projeto, vamos separar esse site atual e criar um novo projeto para transformar/recriar esse tema elegível para o repositório do wordpress.org.

Toda ajuda é muito bem-vinda!
Voltamos a nos reunir (via hangout) todas as terças-feiras às 20h.
Colocamos o link no canal #riodejaneiro no Slack da WP Brasil.

Abs!

**Comment by miguelsmuller** [comment]
OK. Sem problema.
