### ISSUE TITLE
Formulário de contato em 2 colunas em resolução altas

### ISSUE THREAD

**Issue by miguelsmuller** [wp-rio/wp-rio#28]
Implementar melhoria visual no formulário de contato...
Colocando talvez o form em 2 colunas e mudando o css do input...
No PSD tem algum desenho pro input. se tiver posso ajudar aqui...

**Comment by brenoalvs** [comment]
Não temos desenho no PSD, talvez o @cristianoweb possa nos ajudar.
Mas hoje temos poucos campos, não vejo muito o que fazer.

**Comment by cristianoweb** [comment]
@brenoalvs claro que tem o PSD!
https://drive.google.com/open?id=0B5rXuc2rtgf-fnJpZ3FZZFE1bFRuY1g3b1Brb1lCQmV6cTZLa0tpNUF6aDdXeTQ4NmRDdVk

Claro que se precisar de ajustes eu faço e subo novamente.

**Comment by theandersonn** [comment]
Como temos pouco conteúdo deixei a disposição dos inputs como estavam.
Ajustei background-color dos campos, placeholder e responsividade.
