### ISSUE TITLE
Texto e botão sobrepostos na home

### ISSUE THREAD

**Issue by rdlmda** [wp-rio/wp-rio#32]
Não cheguei a ver onde no código está gerando issso, mas só pra constar, tá assim no mobile:

![screenshot_2015-09-15-14-51-40](https://cloud.githubusercontent.com/assets/4602525/9895328/9b3479c4-5c04-11e5-9fcc-dba260eda070.png)

**Comment by brenoalvs** [comment]
Valeu rudá, esqueci de especificar bem isso. Mas basicamente a #26 refere-se a esses problemas.

**Comment by rdlmda** [comment]
Closed as duplicate of #26
