### ISSUE TITLE
Sugestão: Modularização de tarefas (site)

### ISSUE THREAD

**Issue by theandersonn** [wp-rio/wp-rio#48]
Uma sugestão para movimentarmos as pendências aqui do site é varrermos as pendências e modularizarmos as tarefas.

Exemplo:

_Apontar ajustes pontuais_
_Trabalhar na parte responsiva_
_Avaliação da estrutura atual_

Ainda outros aspectos, que talvez possam ser tratados em outro lugar, são as postagens no site; na minha opinião deveríamos centralizar num único lugar.

**O que acham, opiniões.**

**Comment by brenoalvs** [comment]
É o ideal, inclusive já temos alguns ajustes abertos nas issues.

Mas temos coisas mais delicadas:
O principal ponto que temos atualmente é fazer o site da WP Rio funcionar 100% mas, em paralelo, estamos buscando tocar um projeto open-source da comunidade carioca. Só que essas duas coisas não andaram muito bem de mãos dadas até aqui.

Uma opção, talvez polêmica, mas que me atrai hoje, seria separarmos em dois projetos: o tema e o site do WP Rio.

Podemos fazer os hotfixes do site e deixá-lo pronto, com um pouco menos de compromisso com padrões e etc. Afinal, ele já não é nenhum padrão de excelência. Feito isso, podemos analisar o projeto como um todo, ver o que dá para recuperar e iniciar uma segunda etapa de refactor do tema.

Ao finalizar o refactor, colocamos o novo tema 100% no site.
Assim, o site atual seria o nosso MVP, o que acham?

**Comment by gugaalves** [comment]
Tô com o @brenoalvs nessa ai, gostei da ideia dele :)

**Comment by marioernestoms** [comment]
Super apoio isso @brenoalvs acho que temos que deixar ele funcional e tocar em segundo plano um segundo projeto pensando em cada parte, fazendo tudo nos melhores padrões. @gugaalves você poderia gerenciar o projeto? Eu e Breno dividiríamos o front e back e poderíamos procurar um designer que queira apoiar e desenhar o site. Acho que é o melhor caminho dividir em duas etapas.

**Comment by gugaalves** [comment]
Posso sim, contem comigo.

**Comment by vtrpldn** [comment]
Podem contar comigo pra front e back também.

**Comment by theandersonn** [comment]
@brenoalvs tb curti a proposta, eu tinha pensado em algo parecido, mas ao mesmo tempo achei uma medida drástica, como a maioria está de acordo, vamos nessa!

Então é necessário dividirmos as demandas em partes: Temos o site atual que precisa ser administrado com os posts e teremos o desenvolvimento do tema. 

Vamos abrir issues para tratarmos especificamente do desenvolvimento e outra administração dos posts, qual é a vibe de quem vai escrever? Alguma dificuldade em tratar desse assunto aqui no GitHub ou prefere outro ambiente como Trello?

Sugestões?

**Comment by brenoalvs** [comment]
@theandersonn achou drástica em qual ponto?

Quanto a atualização de conteúdo do site, acho que podemos procurar voluntários e simplesmente dar uma conta de autor no site. Acho que o mais importante é quem for escrever sobre o evento ter ao menos comparecido (né?) e que talvez possa tirar mas fotos para enriquecer a postagem.

**Comment by brenoalvs** [comment]
Abri uma nova milestone: Responsive.

Acho que podemos dar uma revisada geral no site e abrir as issues por página comentando todos os problemas, quando houver. Sugestões?

Como o @gugaalves tá viajando, vou começar a fazer (@theandersonn me ajuda nisso?).
Depois de listar tudo, delegamos quem vai fazer o quê.

**Comment by theandersonn** [comment]
@brenoalvs Ajudo sim!

Achei a medida drástica no sentindo de que daria muito trabalho, e que todos discordariam.
Para mim a sua sugestão e o apoio foi uma agradável surpresa. :)

**Comment by gugaalves** [comment]
Tô viajando mas tô vivo e trabalhando :P
Vou tirar algum tempo pra fazer isso, mas podem ir adiantando que depois adiciono minhas observações.
