### ISSUE TITLE
Levantar pontos para a criação de um 'FAQ' para novos contribuidores

### ISSUE THREAD

**Issue by theandersonn** [wp-rio/wp-rio#49]
O que acham de criarmos um readme com instruções para novos colaboradores, com questões como:
- Como estruturar o site WP-Rio em ambiente localhost com os dados do banco e etc...
- Instruções básicas de manusear o Git e GitHub, como manter o fork atualizado com o repositório principal e etc... [exemplo](https://github.com/theandersonn/comandos-git)

**Comment by brenoalvs** [comment]
Uma boa hein @theandersonn, tem também algumas boas práticas descritas aqui neste link:
https://help.github.com/categories/administering-a-repository/

Mas acho uma boa colocarmos essa informação numa Wiki do repositório principal, já que o `README.md` é mais voltado para as informações do projeto em si.

E aí criamos um arquivo `README.md` sobre cada projeto/repositório e um `CONTRIBUTING.md` sobre como abrir um pull request e contribuir.

Mas a primeira etapa seria definir qual será o repositório principal, que podemos decidir na próxima reunião, pois precisamos ver como ficará o deploy do site atual com o @felipepavao que cuida disso.

**Comment by theandersonn** [comment]
@brenoalvs FAQ numa Wiki vai ficar mais centralizado e facil de acessar. :thumbsup:
Temos que levantar quais informações são pertinentes.

**Comment by theandersonn** [comment]
Criei um o milestone [FAQ](https://github.com/wp-rio/wp-rio/milestones/FAQ) e inseri pontos para a criação dos tutoriais que ficarão dentro da Wiki do repositório do novo tema.

Essas sugestões são 12 passos que auxiliarão desde a primeira garfada ao emvio do Pull Request.

**1.** [Fluxo de trabalho - esqueleto do projeto](https://github.com/wp-rio/wp-rio/issues/67)
**2.** [Como forkar o projeto](https://github.com/wp-rio/wp-rio/issues/68) 
**3.** [Como fazer um clone do repositório em ambiente local](https://github.com/wp-rio/wp-rio/issues/69) 
**4.** [Como criar uma nova branch para trabalhar nas modificações em localhost](https://github.com/wp-rio/wp-rio/issues/70) 
**5.** [Como criar e conectar o banco de dados em ambiente localhost](https://github.com/wp-rio/wp-rio/issues/71)
**6.** [Como instalar as dependências do projeto](https://github.com/wp-rio/wp-rio/issues/72) 
**7.** [Setar .htaccess](https://github.com/wp-rio/wp-rio/issues/73) 
**8.** [Setar permissões de pastas e arquivos em ambientes Unix](https://github.com/wp-rio/wp-rio/issues/74) 
**9.** [Como commitar as modificações](https://github.com/wp-rio/wp-rio/issues/75) 
**10.** [Como fazer Push dos commits](https://github.com/wp-rio/wp-rio/issues/76) 
**11.** [Como enviar o Pull Request](https://github.com/wp-rio/wp-rio/issues/77) 
**12.** [Como manter a cópia do projeto atualizada com o repositório original](https://github.com/wp-rio/wp-rio/issues/78) 

Claro! Vamos discutir se esses pontos são pertinentes e como eles ficarão dispostos na wiki.
Para novas sugestões de tutoriais, abrir issue e setar a milestone 'faq'.
