### ISSUE TITLE
[front-page] Implementação responsiva

### ISSUE THREAD

**Issue by theandersonn** [wp-rio/wp-rio#50]
A página front-page é composta pela seções:
- banner
- next-event
- last-meetup
- slides
- partners
- blog-area

**Comment by brenoalvs** [comment]
@theandersonn criei alguns issues sobre problemas de cada seção da homepage

Acho melhor quebrarmos em pequenos problemas, assim ninguém precisa ficar responsável pela home inteira, apesar de ser pouca coisa.

Tenta dividir esse issue em outros problemas menores, como os que encontrei ali e depois fecha esse.

**Comment by theandersonn** [comment]
Feito:
https://github.com/wp-rio/wp-rio/issues/61
