### ISSUE TITLE
Contraste baixo dos links 

### ISSUE THREAD

**Issue by brenoalvs** [wp-rio/wp-rio#52]
Hoje está muito difícil identificar os links na página.
@cristianoweb pode prover uma melhoria de cores pra gente?

Páginas internas
![screen shot 2016-06-20 at 7 06 16 am](https://cloud.githubusercontent.com/assets/5307192/16190446/b3db3eb8-36b5-11e6-966e-88322de56bd1.png)

Página do blog
![screen shot 2016-06-20 at 7 06 31 am](https://cloud.githubusercontent.com/assets/5307192/16190447/b3e12814-36b5-11e6-94c5-3232c8af5fd4.png)

**Comment by cristianoweb** [comment]
(Vamos para a minha primeira interação com o Github!)
Sugiro então trocar a cor de #315c86 (azul) para #f7941d (laranja).

![untitled-1](https://cloud.githubusercontent.com/assets/3214358/16314680/6b1109f4-3955-11e6-9207-68104d0599b4.png)

**Comment by brenoalvs** [comment]
E o texto fica preto, certo?
Atualmente ele é azul, o que confunde com o título também.
