### ISSUE TITLE
Melhorar crop das imagens

### ISSUE THREAD

**Issue by brenoalvs** [wp-rio/wp-rio#53]
Não acho que essa issue seja mandatória, mas podemos tentar corrigir pois melhor muito o visual.

![screen shot 2016-06-20 at 6 57 15 am](https://cloud.githubusercontent.com/assets/5307192/16190523/115ff510-36b6-11e6-8f30-43552c0c1278.png)

**Comment by theandersonn** [comment]
@felipepavao Ficamos com alguns ajustes atravessados com outros.
Esse foi abrangido [aqui](https://github.com/wp-rio/wp-rio/pull/93) e [aqui](https://github.com/wp-rio/wp-rio/pull/88).

Desculpas, a intenção não se intrometer na sua issue.

**Comment by felipepavao** [comment]
Maravilha. Se puder pegar a outra issue, eu te agradecerei. A issue não é minha, é nossa :D

**Comment by theandersonn** [comment]
Valeu, sem problemas! Pode deixar.
