### ISSUE TITLE
Publicações fora de ordem

### ISSUE THREAD

**Issue by brenoalvs** [wp-rio/wp-rio#54]
Não acho este item mandatório, mas melhora muito a UX do site.

![screen shot 2016-06-20 at 6 57 35 am](https://cloud.githubusercontent.com/assets/5307192/16190542/345ecc4e-36b6-11e6-8aae-bcb588cd16d0.png)

**Comment by theandersonn** [comment]
@felipepavao Peguei essa issue pra fazer porque conflitou com um ajuste que eu fiz na home blog e precisei alterar o loop do meetup.
