### ISSUE TITLE
Falta thumbnail padrão em alguns casos

### ISSUE THREAD

**Issue by brenoalvs** [wp-rio/wp-rio#55]
![screen shot 2016-06-20 at 6 54 41 am](https://cloud.githubusercontent.com/assets/5307192/16190598/84fc7dc2-36b6-11e6-94ee-231e5a47f4ae.png)

**Comment by theandersonn** [comment]
@cristianoweb Solta aí no capricho uma thumb 220x165 pra inserirmos como fallback. :kissing_smiling_eyes:
