### ISSUE TITLE
Remover outline

### ISSUE THREAD

**Issue by brenoalvs** [wp-rio/wp-rio#56]
Precisamos desabilitar o outline no focus de alguns elementos da página.

![screen shot 2016-06-20 at 6 55 12 am](https://cloud.githubusercontent.com/assets/5307192/16190624/a5a4d2fe-36b6-11e6-98b3-b5f11e8415f6.png)

**Comment by theandersonn** [comment]
Fechando, PR enviado.  (não mergiar o PR)
https://github.com/wp-rio/wp-rio/pull/85

Essa modificação tb foi abrangida aqui:
https://github.com/wp-rio/wp-rio/pull/80

@leonofre, @brenoalvs
