### ISSUE TITLE
Área "Nosso último encontro" precisa de correções

### ISSUE THREAD

**Issue by brenoalvs** [wp-rio/wp-rio#57]
- Thumbnail não está clicável
- Em resoluções menores o texto quebra

![screen shot 2016-06-20 at 6 50 45 am](https://cloud.githubusercontent.com/assets/5307192/16190664/d1834784-36b6-11e6-8ec3-8cb50458b1af.png)

**Comment by brenoalvs** [comment]
Repassado @leonofre!

**Comment by rodrigocka** [comment]
Deixar o botão com _position: static;_ já resolve?

**Comment by brenoalvs** [comment]
Fechado! @leonofre
