### ISSUE TITLE
Área "Direto do blog" precisa de correções

### ISSUE THREAD

**Issue by brenoalvs** [wp-rio/wp-rio#58]
- Excerpt está muito longo
- Podemos diminuir o botão

![screen shot 2016-06-20 at 6 53 33 am](https://cloud.githubusercontent.com/assets/5307192/16190710/0c43239e-36b7-11e6-97f2-42a96e2438c8.png)

**Comment by gugaalves** [comment]
Pelo o que vi isso está no front-page.php do tema, em https://github.com/wp-rio/wp-rio/blob/master/wp-content/themes/wp-rio/front-page.php#L134 .

A ideia é alterar o tamanho do excerpt só aqui, ou em todo o site?
Sobre o botão, alterar o texto dele pra "Leia mais" resolve o problema da largura do botão?

**Comment by rodrigocka** [comment]
Para o botão, acho que vale alterar como o @gugaalves comentou, já que o botão se adapta ao texto.
Se alterar a propriedade _white-space_ para _normal;_, o resultado não fica bom por conta do _Glyphicon_.

**Comment by leonofre** [comment]
Nesse último commit eu errei o número da issue, mas de qualquer forma já resolvi essa e fiz pull request

**Comment by brenoalvs** [comment]
@leonofre falta diminuir o excerpt

**Comment by theandersonn** [comment]
Fix PR #84
