### ISSUE TITLE
Ajustar padding do formulário de contato em smartphones

### ISSUE THREAD

**Issue by theandersonn** [wp-rio/wp-rio#62]
Em telas de smartphones o formulário está sem espaçamento na direita.
E o título está colado a logo no topo.

![contato-smartphone](https://cloud.githubusercontent.com/assets/5203138/16202435/12c5a978-36ec-11e6-8c71-32b03c94cd9b.png)

**Comment by theandersonn** [comment]
@marioernestoms Fiz o ajuste nesta [issue](https://github.com/wp-rio/wp-rio/issues/28) e por tabela corrigiu a falta de espaçamento.
Foi mal... por atropelar a sua issue e qualquer coisa estamos na área :metal:

**Comment by brenoalvs** [comment]
Boa @theandersonn temos muitos problemas interligados mesmo, vamos nos comunicando para evitar qualquer problema :)

**Comment by marioernestoms** [comment]
otimo @theandersonn tem problema não. :)

**Comment by theandersonn** [comment]
Fix PR #80
