### ISSUE TITLE
Criar um README.md com instruções para montar o ambiente

### ISSUE THREAD

**Issue by brenoalvs** [wp-rio/wp-rio#64]
Para possíveis mantenedores do projeto.

**Comment by theandersonn** [comment]
@brenoalvs Acho que podemos abranger essas instruções na milestone [faq](https://github.com/wp-rio/wp-rio/milestones/FAQ) e esse readme tb seria para novo tema.

O que acha?

**Comment by brenoalvs** [comment]
Passado para o FAQ!
Mas o novo tema vai ter um repositório só dele, então vamos ter readme separados, inclusivo acho melhor, se não pode misturar informações do projeto antigo com o novo!

**Comment by theandersonn** [comment]
@brenoalvs Estive pensando nisso.
Inclusive esse milestone FAQ e as issues ficarão mais apropriadas no novo repositório.
Na próxima reunião podemos ver outras opiniões a respeito e já criar o novo repositório com essas issues e mata-las devagar de acordo com o andamento do projeto.

**Comment by theandersonn** [comment]
Ok! No repositório do novo tema abrimos uma issue especifica para esse readme.
Fechando.
