### ISSUE TITLE
Ajustar as urls de 'Meetup' e 'WordCamp' no menu

### ISSUE THREAD

**Issue by theandersonn** [wp-rio/wp-rio#65]
Os links estão setados como urls absolutas.

**Comment by brenoalvs** [comment]
Peguei esse issue!
Vou tentar usar o menu do WordPress, mas acho que não fizemos isso antes por algum problema técnico.

**Comment by brenoalvs** [comment]
@theandersonn tava vendo aqui o que você quer dizer com URLs absolutas?
Os menus estão editáveis pelo painel, tem esse problema em algum outro lugar?

**Comment by theandersonn** [comment]
@brenoalvs Quando baixa o banco e monta local ficou confuso.
Mas tem a questão de vida util deste tema, talvez não precisemos ficar encucados com essa questão. Já que vamos partir para o novo tema.

**Comment by brenoalvs** [comment]
Beleza, fechando então!
