### ISSUE TITLE
Como criar e conectar o banco de dados em ambiente localhost

### ISSUE THREAD

**Issue by theandersonn** [wp-rio/wp-rio#71]
Explicar os passos para a criação do banco e configuração em ambiente local.

**Comment by taianunes** [comment]
@theandersonn como podemos obter uma cópia do DB para testes locais? Já existe isso pronto?

**Comment by theandersonn** [comment]
@taianunes Opa!
Recebemos uma cópia na reunião de terça passada.

A questão é que as issues pendentes já estão assinadas e por agora esses ajustes concluirão o ciclo deste tema.

Essa issue todas as que estão no milestone FAQ já fazem parte do novo projeto.
https://github.com/wp-rio/wp-rio/issues/49

Novidades na próxima reunião que será confirmada no slack / canal riodejaneiro.
Participe!

**Comment by theandersonn** [comment]
Issue será aberta no repositório do novo tema, seguindo o fluxo:
https://github.com/wp-rio/wp-rio/issues/49
