### ISSUE TITLE
Ajustar botões da Home em smartphones

### ISSUE THREAD

**Issue by leonofre** [wp-rio/wp-rio#82]
![issue](https://cloud.githubusercontent.com/assets/19397230/16496730/ce902e32-3ec9-11e6-8d16-42ddcd95c0f2.jpg)

**Comment by leonofre** [comment]
O espaçamento está pouco ou nenhum nos botões da home em smartphones

**Comment by brenoalvs** [comment]
@leonofre já tem as issues #57 e #58 pra isso. Estamos quebrando os problemas em partes menores.
Elas estão assignadas pra mim, mas se quiser, pode pegar! ;)
