### ISSUE TITLE
Erro na exibição dos posts na Home do Blog

### ISSUE THREAD

**Issue by theandersonn** [wp-rio/wp-rio#86]
Atualmente temos 5 posts publicados e a home do blog está exibindo apenas 3 e também não exibe paginação se for necessário.

http://wprio.org/blog

**Comment by gugaalves** [comment]
Sugestão: deixar fixo no front-page.php e no home.php pegar a quantidade que estiver setada nas configurações no painel.
Ah, bom adicionar paginação também!

**Comment by theandersonn** [comment]
Ah! na front-page.php os 3 posts do blog estão setados no loop.
Fix - Issue #88
