### ISSUE TITLE
Padronizar thumb na home do Blog

### ISSUE THREAD

**Issue by theandersonn** [wp-rio/wp-rio#87]
As thumbs da home blog estão sem padrão, umas preenchem a tela e outras não.
Vamos pradronizar, oque acha @cristianoweb ?

![thumb-wprio](https://cloud.githubusercontent.com/assets/5203138/16629799/adcba712-438d-11e6-9a08-53f0fc605271.jpg)

**Comment by brenoalvs** [comment]
Precisamos ajustar, por algum motivo as imagens estão sendo fixadas com 620 de largura.
Era pra elas serem full-width!

**Comment by theandersonn** [comment]
Olhei como estão setadas as thumbs no functions e estão sem 'true' para determinar o crop e as imagens que estão diferentes são as que possuem proporções diferentes.

Exemplo:
add_image_size( 'entry-large', 940, 350, array( 'center', 'center' ) );

Podemos setar true para forçar o crop e passar um Regenerate Thumbnails.

**Comment by theandersonn** [comment]
Fix PR #93
